name: "Docker Login"
description: "Logs into DockerHub and GitHub Container Registry"
inputs:
  docker_username:
    description: "DockerHub Username"
    required: true
  docker_password:
    description: "DockerHub Password"
    required: true
  github_token:
    description: "GitHub Token for GitHub Container Registry"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
