name: "Determine Branch Name and Set Variables"
description: "Determines the branch name and sets Docker image tags based on the branch or tag."

runs:
  using: "composite"
  steps:
    - name: Determine Branch Name and Set Variables
      id: prep
      shell: bash
      run: |
        if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            if [[ "${GITHUB_REF}" == refs/heads/*/* ]] ; then
                git_branch="${GITHUB_REPOSITORY/docker-/}:$(echo $GITHUB_REF | sed "s|refs/heads/||g" | sed "s|/|-|g")"
            else
                git_branch=${GITHUB_REF#refs/heads/}
            fi

            case "${git_branch}" in
                "main" | "master" )
                    if [ "${{ env.LATEST }}" = "TRUE" ] || [ "${{ env.DISTRO_VARIANT }}" = "${DISTRO_VARIANT}" ]; then
                        image_latest=",${GITHUB_REPOSITORY}:latest"
                    fi
                    branch_tag="${GITHUB_REPOSITORY}:${DISTRO_VARIANT},${GITHUB_REPOSITORY}:${DISTRO_VARIANT}-latest${image_latest}"
                ;;
                "develop" )
                    branch_tag="${GITHUB_REPOSITORY}:develop"
                ;;
            esac
        fi

        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            git_tag="${GITHUB_REPOSITORY}:${DISTRO_VARIANT}-$(echo ${GITHUB_REF} | sed 's|refs/tags/||g')"
        fi

        if [ -n "${branch_tag}" ] && [ -n "${git_tag}" ]; then
            image_tags=${branch_tag},${git_tag}
        else
            image_tags="${branch_tag}${git_tag}"
        fi

        echo "dockerhub_repo=${GITHUB_REPOSITORY/docker-/}" >> $GITHUB_ENV
        dockerhub_images=$(echo "${image_tags}" | sed "s|${GITHUB_REPOSITORY}|docker.io/${GITHUB_REPOSITORY/docker-/}|g")
        ghcr_images=$(echo "${image_tags}" | sed "s|${GITHUB_REPOSITORY}|ghcr.io/${GITHUB_REPOSITORY}|g")
        echo "container_images=${dockerhub_images},${ghcr_images}" >> $GITHUB_OUTPUT
